using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Scare.Core.Model
{
    public enum FacialActionCodingType
    {
        NeutralFace = 0,
        InnerBrowRaiser = 1,
        OuterBrowRaiser = 2,
        BrowLowerer = 4,
        UpperLidRaiser = 5,
        CheekRaiser = 6,
        LidTightener = 7,
        LipsTowardEachOther = 8,
        NoseWrinkler = 9,
        UpperLipRaiser = 10,
        NasolabialDeepener = 11,
        LipCornerPuller = 12,
        SharpLipPuller = 13,
        Dimpler = 14,
        LipCornerDepressor = 15,
        LowerLipDepressor = 16,
        ChinRaiser = 17,
        LipPucker = 18,
        TongueShow = 19,
        LipStretcher = 20,
        NeckTightener = 21,
        LipFunneler = 22,
        LipTightener = 23,
        LipPressor = 24,
        LipPart = 25,
        JawDrop = 26,
        MouthStretch = 27,
        LipSuck = 28,
        JawThrust = 29,
        JawSideways = 30,
        JawClencher = 31,
        LipBite = 32,
        CheekBlow = 33,
        CheekPuff = 34,
        CheekSuck = 35,
        TongueBulge = 36,
        LipeWipe = 37,
        NostrilDilator = 38,
        NostrilCompressor = 39,
        Sniff = 40,
        GlabellaLowerer = 41,
        InnerEyebrowLowerer = 42,
        EyesClosed = 43,
        EyebrowGatherer = 44,
        Blink = 45,
        Wink = 46,
        Speech = 50,
        HeadTurnLeft = 51,
        HeadTurnRight = 52,
        HeadUp = 53,
        HeadDown = 54,
        HeadTiltLeft = 55,
        HeadTiltRight = 56,
        HeadForward = 57,
        HeadBack = 58,
        HeadShakeUpAndDown = 59,
        HeadShakeSideToSide = 60,
        EyesTurnLeft = 61,
        EyesTurnRight = 62,
        EyesUp = 63,
        EyesDown = 64,
        Walleye = 65,
        CrossEye = 66,
        UpwardRollingOfEyes = 68,
        EyesPositionedToLookAtOtherPerson = 69,
        BrowsAndForeheadNotVisible = 70,
        EyesNotVisible = 71,
        LowerFaceNotVisible = 72,
        EntireFaceNotVisible = 73,
        Unscorable = 74,
        Swallow = 80,
        Chewing = 81,
        ShoulderShrug = 82,
        HeadUpwardAndToTheSide = 83,
        HeadShakeBackAndForth = 84,
        HeadNodUpAndDown = 85,
        Flash = 91,
        PartialFlash = 92,
        ShiverTremble = 97,
        FastUpDownLook = 98,
        EntireFaceVisible = 99,
    }
}
